import React from "react";


const PrivacyPolicy = () => {
  return (
    <>


      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-10 ">
            <div className="about_part_text">
              <div className="about">
                <h2>
                  Privacy <span className="black">Policy</span>
                </h2>
                <p>
                  This Privacy Policy explains the policy regarding the
                  collection, use, disclosure, and transfer of your information
                  by Truxcargo Private Limited and its affiliates (collectively
                  “we/us/ our/truxcargo”) through www.truxcargo.com (“Site”) for
                  all the services provided by us ("Services"). This policy may
                  change as we update, improve, and expand the Services, so
                  please check it periodically. By accessing the Site of
                  Truxcargo or otherwise using the Services, you consent to
                  collection, storage, and use of the personal information you
                  provide (including any changes thereto as provided by you) for
                  any of the Services offered by us. This document is an
                  electronic record in terms of Information Technology Act, 2000
                  (“IT Act, 2000”), the applicable rules thereunder and the
                  provisions pertaining to electronic records in various
                  statutes as amended by the Information Technology Act, 2000.
                  This electronic record is generated by a computer system and
                  does not require any physical or digital signatures. This
                  Privacy Policy is a legally binding document between the User
                  (“you,” “your,” “yourself”) of the Site and Truxcargo Private
                  Limited. Please read the terms of this privacy policy very
                  carefully and should you disagree with the terms of this
                  policy, please do not use the website.
                </p>
              </div>
              <h3 className="mt-5">Application of the Privacy Policy:</h3>
              <p>
                This Privacy Policy stipulates the approach taken by us towards
                the personal information and data that we may collect about you
                or you may disclose to us, when you visit this Site,
                electronically respond to our online advertisements or when you
                send us communications, queries, or apply for job or for
                partnering with us via any computer, mobile or other similar
                electronic devices. It does not apply to information we collect
                in other ways e.g., when you are dealing with our employees or
                authorised representatives otherwise than use or access of this
                Website or over the telephone.
              </p>
              <p className="serinfo">
                This Privacy Policy is limited to information and data collected
                on this Site, our online advertisements, and electronic
                communications. Our Privacy Policy does not apply when you leave
                our Site, including third-party websites where our online
                advertisements are displayed or links to third-party websites
                which we do not operate or control. Please read the Privacy
                Policy and terms and conditions of these third-party websites
                and decide whether they satisfactorily protect your rights and/
                or interests.
              </p>
              <p className="serinfo">
                Apart from the sources mentioned above, we collect and process
                the information from you from the following sources to provide
                better services to all our users.
              </p>
              <p className="serinfo">i) Registration data</p>
              <p className="serinfo">
                This includes basic contact information such as name, gender,
                age, address, pin code, contact number, occupation, interests,
                and email address etc. provided at the time of registration to
                use the Site and seeking or obtaining Services from us.
              </p>
              <p className="serinfo">ii) Paid service data</p>
              <p className="serinfo">
                When you make any payment for the Services, TRUXCARGO or its
                payment gateway provider may collect your purchase, address or
                billing information, including your credit card number and
                expiration date etc.
              </p>
              <p className="serinfo">iii) Voluntary information</p>
              <p className="serinfo">
                Truxcargo may collect additional information at other times,
                including but not limited to, when you provide feedback, change
                your Error message need to be informative and display clearly
                content or email preferences, respond to a survey, or
                communicate with Truxcargo.
              </p>

              <h3>Cookies</h3>
              <p className="serinfo">
                Truxcargo use data collection devices such as "cookies" on
                certain pages of its Site. Cookies are small files which are
                stored on your hard drive that assist us in providing customized
                services. We also offer certain features that are only available
                through the use of a "cookie". Cookies help us to provide
                information, which is targeted to your interests. Cookies may be
                used whether you register with us or not.
              </p>
              <h3>Use of your information</h3>
              <p className="serinfo">
                The Information as supplied by you enables our need to be
                informative and display clearly the Services and provide you the
                most user-friendly experience. All required information is
                service dependent, and we may use the above said user
                Information to, maintain, protect, and improve the Services and
                for developing new services. We may also use your email address
                or other personally identifiable information to send commercial
                or marketing messages without your consent [with an option to
                subscribe / unsubscribe (where feasible)]. We may, however, use
                your email address without further consent for non-marketing or
                administrative purposes (such as notifying you of major changes,
                for customer service purposes, billing, etc.).
              </p>
              <p className="serinfo">
                Without limitation to the foregoing, your information may be
                used for the following purposes ("Purposes”):
              </p>
              <p></p>
              <ul>
                <ul>
                  <li>
                    To develop, enhance, market, sell or provide our services,
                    or those of companies with which we have a commercial
                    relationship
                  </li>
                  <li>
                    To provide tips or guidance on how to use our website,
                    inform you of new features on our website, or provide other
                    information that may be of interest to you
                  </li>
                  <li>
                    To evaluate credit standing and to match credit bureau or
                    credit reporting agency information; to investigate, detect
                    and protect ourselves and other third parties against error,
                    negligence, breach of contract, fraud, theft and other
                    illegal activities
                  </li>
                  <li>
                    To affect a corporate transaction, in connection with the
                    sale, merger, spin-off or other corporate reorganization of
                    our corporation, where the information is provided to the
                    new controlling entity in regular course of business
                  </li>
                  <li>
                    To audit compliance with our policies and contractual
                    obligations
                  </li>
                  <li>
                    following up on any service requirement which you have shown
                    interest in;
                  </li>
                  <li>updating our records about you;</li>
                  <li>understanding your requirement;</li>
                  <li>
                    conducting background verification checks in case where you
                    have applied for job with us;
                  </li>
                  <li>
                    crime or fraud detection, prevention, and prosecution;
                  </li>
                  <li>complying with laws or regulations;</li>
                  <li>
                    research and statistical analysis with the aim of improving
                    our services;
                  </li>
                  <li>
                    knowing you more before we respond to your requirement;
                  </li>
                  <li>handling queries and complaints; and</li>
                  <li>other incidental services, purpose, or requirements</li>
                </ul>
              </ul>
              <p></p>
              <p className="serinfo">
                Additionally, without limitation to the foregoing, we need all
                files access for internal features:
              </p>

              <h3>Disclosure of your information</h3>
              <p className="serinfo">
                Truxcargo shares your information with any third party in the
                following limited circumstances:
              </p>
              <ul>
                <li>While using your information for the Purposes</li>
                <li>
                  When it is requested or required by law or by any court or
                  governmental agency or authority to disclose, for the purpose
                  of verification of identity, or for the prevention, detection,
                  investigation including cyber incidents, or for prosecution
                  and punishment of offences. These disclosures are made in good
                  faith and belief that such disclosure is reasonably necessary
                  for enforcing these terms or for complying with the applicable
                  laws and regulations
                </li>
                <li>
                  Truxcargo proposes to share such information within its group
                  companies and employees of such group companies for the
                  purpose of processing personal information on its behalf. We
                  also ensure that these recipients of such information agree to
                  process such information based on our instructions and in
                  compliance with this Privacy Policy and any other appropriate
                  confidentiality and security measures
                </li>
                <li>
                  Truxcargo may disclose information to third parties to detect,
                  prevent or otherwise address fraud, security or technical
                  issues or protect the rights, property or safety of us, our
                  users, or others or in order to enforce or apply our terms of
                  use.
                </li>
              </ul>
              <p>
                We will not otherwise disclose your information to third parties
                unless we have your permission, or we are under a legal or
                similar obligation.
              </p>
              <h3>Information Security</h3>
              <p className="serinfo">
                Truxcargo use data collection devices such as "cookies" on
                certain pages of its Site. Cookies are small files which are
                stored on your hard drive that assist us in providing customized
                services. We also offer certain features that are only available
                through the use of a "cookie". Cookies help us to provide
                information, which is targeted to your interests. Cookies may be
                used whether you register with us or not.
              </p>
              <p className="serinfo">
                The Internet is not a secure form of communication and sending
                and receiving information over the Internet carries with it
                risks including the risk of access and interference by
                unauthorised third parties. It is your responsibility to
                maintain the secrecy of any user ID and login password you hold.
              </p>
              <p className="serinfo">
                Truxcargo take appropriate security measures to protect against
                unauthorized access to or unauthorized alteration, disclosure,
                or destruction of data. These include internal reviews of our
                data collection, storage and processing practices and security
                measures, including appropriate encryption and physical security
                measures to guard against unauthorized access to systems where
                we store personal data. Though all measures have been taken to
                ensure the safety and security of your information you will
                appreciate that there could be instances beyond our control
                which could result in unwarranted disclosure of your personal
                information, and you fully understand the risks associated with
                disclosure of personal information on such forum.
              </p>
              <p className="serinfo">
                Although Truxcargo shall make all reasonable attempts to
                eliminate and exclude viruses from this Site, Truxcargo does not
                ensure or accept any liability in respect thereof. By accessing
                this Site, you accept this. The Parties using this website may
                take suitable precautions before downloading information.
              </p>
              <p className="serinfo">
                We do not accept responsibility or liability for the
                confidentiality, security, or integrity of your information in
                connection with its transmission over the Internet.
              </p>
              <p className="serinfo">
                In order to maintain the security of our systems, protect our
                staff, record transactions, and, in certain circumstances, to
                prevent and detect crime or unauthorised activities, we reserve
                the right to monitor web and email traffic into and out of our
                domain.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
