const DATA = [{
        id: 0,
        image: "/image/services/service1.svg",
        title: "Ecommerce-Retail Logistics Solutions",
        content: "Shipment cost is what acquires a major part of your costs in eCommerce. Reducing costs, availing you with early COD, maximum serviceable pin codes and reducing shipment TAT are our USP.Managing Logistics is the greatest challenge for any eCommerce company especially in a country like India with a vast territory. With the advancements in eCommerce, even the logistics industry is witnessing innovation and implementing technological support to cater to such high demands",
        contentfull: "<p>Shipment cost is what acquires a major part of your costs in eCommerce. Reducing costs, availing you with early COD, maximum serviceable pin codes and reducing shipment TAT are our USP <br/><br/> Managing Logistics is the greatest challenge for any eCommerce company especially in a country like India with a vast territory. With the advancements in eCommerce, even the logistics industry is witnessing innovation and implementing technological support to cater to such high demands.<br/><br/> And now it is possible for online buyers to track their consignment from the date of dispatch from the factory or warehouse till its’ delivery at the consignee’s address. The task of delivering shipments becomes even more strenuous during weather disturbances such as rainy season or when extensive areas get flooded and many bridges are damaged.<br/><br/> Before the advent of the eCommerce industry, retailers sourced goods either from manufacturers or distributors. And now that we have a plethora of online shopping stores, the intermediaries cease to exist, leading to deals directly done between the supplier and end-user: C&F (clearing and forwarding agents), distributors, dealers, and retailers have no role in this direct selling process.<br/> <br/> With these intermediaries removed, eCommerce shipping has become an essential part of the supply chain management and emerged as a highly specialized service with the majority of them being managed by eCommerce companies themselves.<br/> <br/>Logistics is a congregation of various processes such as inventory management, warehousing, packaging, labeling, billing, shipping, payment collection, return, and exchange. All these put together turn into an exigent task, that requires a full-proof strategy to be accomplished. Apart with these, logistics also requires thorough knowledge about territories, roads and road conditions, regulations regarding the movement of goods, and transport laws. The principal purpose of creating a logistics unit is much to deliver parcels much faster, safer, and more accurately.</p> <h5>How eCommerce Logistics Works</h5> <p>A logistics company functions in two directions:  </p> <p>Forward Direction – Distribution and delivery of goods to buyers.</p> <p>Reverse Direction – Exchanging or replacement of defective, damaged or wrong shipments.</p>"
    },

    {
        id: 1,
        image: "/image/services/service2.svg",
        title: "Document Courier",
        content: "Send papers and documents directly to your client  with our courier services specialised in legal and accountancy sectors. We understand your industry’s needs and are fully prepared to organise worldwide envelope deliveries with signature upon reception and last-minute pick-up options. Book your legal document delivery service with TRUXCARGO, and our experts will arrange everything on your behalf.",
        contentfull: "<p>Send papers and documents directly to your client  with our courier services specialised in legal and accountancy sectors. We understand your industry’s needs and are fully prepared to organise worldwide envelope deliveries with <b>signature upon reception</b> and <b>last-minute pick-up</b> options. Book your legal document delivery service with TRUXCARGO, and our experts will arrange everything on your behalf.</p>  <h5>Your legal document deliveries are always tracked!</h5> <p>At Truxcargo, we make reliability a top priority. When sending sensitive or confidential papers through our documents courier services, your envelope will always receive a unique tracking number so you can <b>follow its progress until the recipient.</b> Through our digital tracking tool, you will get real-time updates provided by the logistics company responsible for your papers.</p>",
    },
    {
        id: 2,
        image: "/image/services/service3.svg",
        title: "B2C Air Freight",
        content: "If time so priority Air fright is the solution for your shipment ,we delivery daily with  first class Airline will be choice for your cargo, connecting flight also available.  Air freight is another term for air cargo that is, the shipment of goods through an air carrier.Air transport services are the most valuable when it comes to moving express shipments around the globe. Just like the commercial or passenger airlines, air freight flies in the same gateways.",
        contentfull: "<p>If time so priority Air fright is the solution for your shipment ,we delivery daily with  first class Airline will be choice for your cargo, connecting flight also available.  Air freight is another term for air cargo that is, <b>the shipment of goods through an air carrier.</b> Air transport services are the most valuable when it comes to moving express shipments around the globe. Just like the commercial or passenger airlines, air freight flies in the same gateways.<br/> <br/>Working with carefully selected carriers, we operate with schedules on all the world’s major routes so you can plan with certainty and become more efficient. We offer a range of highly flexible products which allow a choice of delivery speeds to best suit your requirements.</p>",
    },
    {
        id: 3,
        image: "/image/services/service4.svg",
        title: "Full Truck Load",
        content: "Full truckload, or FTL, is a shipping mode where one truck is responsible for a single shipment from one point to another. In an FTL shipment, the truck travels from point A to point B, making the transit times faster, but also a more expensive mode. Full Truckload (FTL) freight logistics help you move high-volume and high-capacity orders faster. This service is suitable for a business requiring a full truck across long distances. ",
        contentfull: "<p>Full truckload, or FTL, is a shipping mode where one truck is responsible for a single shipment from one point to another. In an FTL shipment, the truck travels from point A to point B, making the transit times faster, but also a more expensive mode. Full Truckload (FTL) freight logistics help you move high-volume and high-capacity orders faster. This service is suitable for a business requiring a full truck across long distances. </p> <h6>With Full Truck Load, you can Ship large items effortlessly </h6> <p>Leverage our network of experienced delivery partners</p> <p>Ensure that your shipment is pilferage-proof at all touchpoints</p> <p>Deliver your shipments faster</p> <h6>What are some advantages of shipping Full Truckload? </h6> <p>Most efficient mode of transportation for large shipments </p> <p>Most cost effective mode for shipments over a certain size</p> <p> Less size and weight restrictions</p> <p>Faster transit times than consolidated or less-than-truckload shipments</p> <p> Direct move from origin to destination</p> <p>Less handling and less likely to be lost or damaged as it stays with one truck driver/handler </p>",
    },
    {
        id: 4,
        image: "/image/services/service5.svg",
        title: "Part Truck Load",
        content: "A part load describes goods which only fill a truck partially. In essence, the quantity of the shipment is bigger than the Less Than Truckload (LTL) shipment. Also, the shipment cannot fully occupy a truck i.e. its capacity is much lower than a Full Truckload (FTL) shipment. Part Truckload (PTL) freight logistics help you move your products by sharing space with other businesses shipping along the same line haul. Share the load and pay only for the freight space you occupy.. ",
        contentfull: "<p>A part load describes goods which only fills a truck partially. In essence, the quantity of the shipment is bigger than the Less Than Truckload (LTL) shipment. Also, the shipment cannot fully occupy a truck i.e. its capacity is much lower than a Full Truckload (FTL) shipment. Part Truckload (PTL) freight logistics help you move your products by sharing space with other businesses shipping along the same line haul. Share the load and pay only for the freight space you occupy.</p> <h6>With Part Truck Load, you can Pay only for the freight space used</h6> <p>Shorten your delivery time with door to door service</p> <p>Safely deliver shipments across the country</p> <p>Grow your business by reaching even the remotest corners</p> <h5>What makes Truxcargo the most preferred ?</h5> <p>Your consignment will remain safe and intact from the time of pick-up to delivery.</p> <p>Our fleet of trucks is managed by a professional team so very less or no chances of error.</p> <p>GPS enabled part load trucks to provide you with real-time updates of your consignment.</p> <p>Best part load-services at minimized operational cost.</p> <p>We use advanced transport technology to make transportation smooth and easy.</p>"
    },
    {
        id: 5,
        image: "/image/services/service6.svg",
        title: "Hire a Fleet",
        content: "With our all-new upgrade, you may enjoy a hassle-free fleet rental experience. New features in the Truxcargo Panel to improve user experience. With FLT and LTL services available. Our client panel allows for easy booking and online tracking.",
        contentfull: "<p>With our all-new upgrade, you may enjoy a hassle-free fleet rental experience. New features in the Truxcargo Panel to improve user experience. With FLT and LTL services are available. Our client panel allows for easy booking and online tracking.</p> <p>The Truxcargo Panel is coming with new feature which tells about the dedicated hours on providing with a better user experience by enhancing some of the essential features of the platform. See better than ever how Hire a Fleet can help with the FLT and LTL services. With the online tracking and easy to book through our client panel.</p> ",
    },
];
export default DATA